---
- name: create ovs upgrade scripts
  include: create-scripts.yaml
  tags: create_scripts

- name: upgrade ovs package
  shell: "bash {{ ovs_package_upgrade_script }}"
  tags: upgrade_package

- name: ovs-2.7 config
  include_tasks: ovs-2-7.yaml
  tags: config_2_7
  when: "{{ target_ovs_version|float >= 2.7 }}"

- name: ovs-2.8 config
  include_tasks: ovs-2-8.yaml
  tags: config_2_8
  when: "{{ target_ovs_version|float >= 2.8 }}"

- name: reboot server
  include_tasks: reboot.yaml
  when: manual_reboot|bool
