---
- name: install dependency packages
  become: true
  yum:
    name: git
    state: present

- name: clone tripleo-repos
  become: true
  git:
    repo: "{{ tripleo_repos_url }}"
    dest: /root/tripleo-repos
    clone: yes
    force: yes

- name: install tripleo-repos
  become: true
  shell: "cd /root/tripleo-repos; python setup.py install"

- name: switch repo to master which contains latest ovs
  become: true
  shell: "tripleo-repos -b master current"

- name: update ovs to latest
  become: true
  yum:
    name: openvswitch
    state: latest

- name: switch repo back
  become: true
  shell: "tripleo-repos -b newton current"

- name: add ovs-extra/dev-args in dpdk network config file
  become: true
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-dpdk0
    line: 'OVS_EXTRA="set Interface dpdk0 options:dpdk-devargs=0000:06:00.1"'
    state: present

- name: config ovs default.conf
  become: true
  shell: sed -i 's/^\(OVS_USER_ID=".*\)"/OVS_USER_ID="openvswitch:hugetlbfs"/g' /etc/openvswitch/default.conf

- name: config libvirt qemu.conf
  become: true
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    line: {{ item }}
    state: present
  with_items:
    - 'user = "openvswitch"'
    - 'group = "hugetlbfs"'

- name: add hugetlbfs group
  become: true
  group:
    name: hugetlbfs
    state: present

- name: add openvswitch user
  become: true
  user:
    name: openvswitch
    shell: /sbin/nologin
    comment: "OpenvSwitch Daemons"
    home: /
    system: yes
    group: hugetlbfs

- name: change owner and group of openvswitch files
  become: true
  file:
    path: "{{ item.name }}"
    owner: openvswitch
    group: hugetlbfs
    recurse: yes
  with_items:
    - name: "{{ ovs_config_dir }}"
    - name: "{{ ovs_log_dir }}"
    - name: "{{ ovs_run_dir }}"
    
- name: change vfio group
  become: true
  file:
    path: /dev/vfio
    group: hugetlbfs
    recurse: yes
