---
- block:
  - name: set dpdk_ports_defined
    set_fact:
      dpdk_ports_defined: true
    when: dpdk_ports is defined

  - name: retrieve dpdk_ports mapping dict
    include_tasks: dpdk_ports.yml
    when: dpdk_ports_defined is not defined

  - name: add ovs-extra/dev-args in dpdk network config file
    become: true
    lineinfile:
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.key }}"
      line: 'OVS_EXTRA="set Interface {{ item.key }} options:dpdk-devargs={{ item.value }}"'
      state: present
    with_dict: "{{ dpdk_ports }}"
  when: dpdk_enabled|bool
